# VERSION 2015.09.15
# 基于CentOS:7创建基础镜像
# 1.默认启动ssh服务 port:22 root:123456
#
#

FROM omnbmh/centos7-ssh:beta_0.2

MAINTAINER dezhichen<dezhichen@creditease.cn>

RUN yum install -y bind bind-utils
RUN yum clean all

CMD /usr/sbin/sshd -D
