# VERSION 2015.07.31
FROM centos:5

# sign
MAINTAINER c8d8z8@gmail.com

# ENV setting# VERSION 2015.07.31
FROM centos:5

# sign
MAINTAINER c8d8z8@gmail.com

# ENV setting
ENV APP_PATH /app

RUN mkdir -p "$APP_PATH"
# install java tomcat tar file auto unzip
ADD ./software/apache-tomcat-8.0.24.tar.gz $APP_PATH
ADD ./software/jdk-7u80-linux-x64.gz $APP_PATH

WORKDIR $APP_PATH
# fix sshd can't start
RUN set -x \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' \
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

CMD ["/usr/sbin/sshd", ""]

ENV APP_PATH /app
ENV BAK_PATH /app/bak

run mkdir -p "$APP_PATH"
RUN mkdir -p "$SOFT_PATH"
# prepare software 
COPY ./software/apache-tomcat-8.0.24.tar.gz $BAK_PATH
COPY ./software/jdk-7u80-linux-x64.gz $BAK_PATH

WORKDIR $APP_PATH
#install java tomcat
RUN set -x \
    && tar zxvf $SOFT_PATH/jdk-7u80-linux-x64.gz
    && tar zxvf $SOFT_PATH/apache-tomcat-8.0.24.tar.gz
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key   

CMD ["/usr/sbin/sshd", ""]
