# VERSION 2015.09.01
# 基于CentOS:7创建基础镜像
# 1.默认启动ssh服务 port:22 root:123456
#
#

FROM centos:7

MAINTAINER dezhichen<dezhichen@creditease.cn>

RUN yum clean all
RUN yum update -y
RUN yum install -y openssh-server openssh-clients
RUN yum clean all

# fix sshd can't start on centos 7
RUN set -x \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' \
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

#RUN useradd ussh
RUN echo "root:123456" | chpasswd  

CMD /usr/sbin/sshd -D
